import type {
  AppNotification,
  Equipment,
  EquipmentRequest,
  MaintenanceSchedule,
  Ticket,
  User,
} from "@/lib/types";

// ---------------------------------------------------------------------------
// Users
// ---------------------------------------------------------------------------

export const users: User[] = [
  {
    id: "u1",
    name: "Farhan Ahmed",
    initials: "FA",
    role: "Super Admin",
    organization: "NGGL",
    email: "farhan.ahmed@nggl.com",
    status: "Active",
  },
  {
    id: "u2",
    name: "Nusrat Jahan",
    initials: "NJ",
    role: "Manager",
    organization: "NGGL",
    email: "nusrat.jahan@nggl.com",
    status: "Active",
  },
  {
    id: "u3",
    name: "Engr. Abdul Karim",
    initials: "AK",
    role: "Engineer",
    organization: "NGGL",
    email: "abdul.karim@nggl.com",
    status: "Active",
  },
  {
    id: "u4",
    name: "Engr. Rakib Hasan",
    initials: "RH",
    role: "Engineer",
    organization: "NGGL",
    email: "rakib.hasan@nggl.com",
    status: "Active",
  },
  {
    id: "u5",
    name: "Engr. Shirin Sultana",
    initials: "SS",
    role: "Engineer",
    organization: "NGGL",
    email: "shirin.sultana@nggl.com",
    status: "Inactive",
  },
  {
    id: "u6",
    name: "Kamal Hossain",
    initials: "KH",
    role: "Biman Admin",
    organization: "Biman",
    email: "kamal.hossain@biman-airlines.com",
    status: "Active",
  },
];

export const engineers = users.filter((u) => u.role === "Engineer");

// ---------------------------------------------------------------------------
// Equipment
// ---------------------------------------------------------------------------

export const hourMeterServiceOptions: { label: string; hours: number }[] = [
  { label: "500 HOUR-B-SVC", hours: 500 },
  { label: "1000 HOUR-C -SVC", hours: 1000 },
  { label: "2000 HOUR-D-SVC", hours: 2000 },
  { label: "V-SVC - 6 MONTHS", hours: 4380 },
];

export const nextAssetNo = (list: Equipment[]) => {
  const numbers = list
    .map((item) => Number.parseInt(item.assetNo.replace(/\D/g, ""), 10))
    .filter((n) => !Number.isNaN(n));
  const next = (numbers.length ? Math.max(...numbers) : 0) + 1;
  return `BGM-${String(next).padStart(3, "0")}`;
};

export const equipment: Equipment[] = [
  {
    id: "eq1",
    assetNo: "BGM-001",
    type: "Belt Loader",
    manufacturer: "TLD",
    model: "NBL-800",
    bimanSerialNo: "12345",
    TLDSerialNo: "T103433",
    location: "HSIA - Apron Bay 4",
    status: "Available",
    actualGTDate: "2020-01-15",
    hourMeter: 250,
    shipDate: "2020-01-15",
    shippingStatus: "COMMISSIONED",
    emissionRatting: "Tier3/Stage 3A",
    equipmentPhotos: [],
    specifications: [
      { label: "Belt Capacity", value: "1,600 kg" },
      { label: "Engine", value: "Kubota V2403" },
      { label: "Belt Speed", value: "0.5 m/s" },
      { label: "Lift Height", value: "0.6 - 4.2 m" },
    ],
    documents: [
      { id: "d1", name: "NBL-800 Operator Manual.pdf", type: "Manual", uploadedDate: "2020-01-20" },
      { id: "d2", name: "Insurance Certificate 2026.pdf", type: "Insurance", expiryDate: "2026-11-30", uploadedDate: "2025-12-01" },
    ],
  },
  {
    id: "eq2",
    assetNo: "BGM-002",
    type: "Tug Tractor",
    manufacturer: "TLD",
    model: "TMX-150",
    bimanSerialNo: "54321",
    TLDSerialNo: "T44084",
    location: "HSIA - Apron Bay 2",
    status: "Under Maintenance",
    actualGTDate: "2019-06-10",
    equipmentPhotos: [],
    specifications: [
      { label: "Towing Capacity", value: "45,000 kg" },
      { label: "Engine", value: "Cummins QSB 4.5" },
      { label: "Transmission", value: "Automatic, 4-speed" },
    ],
    documents: [
      { id: "d3", name: "TMX-150 Service Manual.pdf", type: "Manual", uploadedDate: "2019-06-15" },
    ],
  },
  {
    id: "eq3",
    assetNo: "BGM-003",
    type: "Ground Power Unit (GPU)",
    manufacturer: "TLD",
    model: "GPU-90",
    bimanSerialNo: "67890",
    TLDSerialNo: "T21515",
    location: "HSIA - Apron Bay 6",
    status: "Available",
    actualGTDate: "2021-03-22",
    equipmentPhotos: [],
    specifications: [
      { label: "Output", value: "90 kVA, 115/200V, 400Hz" },
      { label: "Engine", value: "John Deere 4045" },
    ],
    documents: [
      { id: "d4", name: "GPU-90 Wiring Diagram.pdf", type: "Manual", uploadedDate: "2021-03-25" },
      { id: "d5", name: "Insurance Certificate 2026.pdf", type: "Insurance", expiryDate: "2026-07-10", uploadedDate: "2025-07-15" },
    ],
  },
  {
    id: "eq4",
    assetNo: "BGM-004",
    type: "Passenger Steps",
    manufacturer: "EINSA",
    model: "PS-4500",
    bimanSerialNo: "11111",
    TLDSerialNo: "T-PS-4500",
    location: "HSIA - Apron Bay 1",
    status: "Available",
    actualGTDate: "2018-09-05",
    equipmentPhotos: [],
    specifications: [
      { label: "Max Sill Height", value: "5.6 m" },
      { label: "Steps", value: "Dual-lane, 15 steps" },
    ],
    documents: [
      { id: "d6", name: "PS-4500 Operator Manual.pdf", type: "Manual", uploadedDate: "2018-09-10" },
    ],
  },
  {
    id: "eq5",
    assetNo: "BGM-005",
    type: "Air Conditioning Unit (ACU)",
    manufacturer: "TLD",
    model: "ACU-60",
    bimanSerialNo: "22222",
    TLDSerialNo: "T103433",
    location: "HSIA - Apron Bay 3",
    status: "Out of Service",
    actualGTDate: "2017-11-30",
    equipmentPhotos: [],
    specifications: [
      { label: "Cooling Capacity", value: "60 tons" },
      { label: "Engine", value: "Kubota V3800" },
    ],
    documents: [
      { id: "d7", name: "ACU-60 Maintenance Guide.pdf", type: "Manual", uploadedDate: "2017-12-05" },
    ],
  },
  {
    id: "eq6",
    assetNo: "BGM-006",
    type: "Tug Tractor",
    manufacturer: "TLD",
    model: "TMX-150",
    bimanSerialNo: "54322",
    TLDSerialNo: "T44664",
    location: "HSIA - Apron Bay 2",
    status: "Available",
    actualGTDate: "2020-07-19",
    equipmentPhotos: [],
    specifications: [
      { label: "Towing Capacity", value: "45,000 kg" },
      { label: "Engine", value: "Cummins QSB 4.5" },
    ],
    documents: [],
  },
  {
    id: "eq7",
    assetNo: "BGM-007",
    type: "Pushback Tractor",
    manufacturer: "TLD",
    model: "TPX-400",
    bimanSerialNo: "33344",
    TLDSerialNo: "T82687",
    location: "HSIA - Apron Bay 5",
    status: "Available",
    actualGTDate: "2022-02-11",
    equipmentPhotos: [],
    specifications: [
      { label: "Max Towbarless Capacity", value: "400,000 kg" },
      { label: "Engine", value: "Cummins QSL9" },
    ],
    documents: [
      { id: "d8", name: "TPX-400 Manual.pdf", type: "Manual", uploadedDate: "2022-02-15" },
    ],
  },
  {
    id: "eq8",
    assetNo: "BGM-008",
    type: "Air Start Unit (ASU)",
    manufacturer: "TLD",
    model: "ASU-50",
    bimanSerialNo: "44455",
    TLDSerialNo: "T21976",
    location: "HSIA - Apron Bay 6",
    status: "Available",
    actualGTDate: "2019-12-01",
    equipmentPhotos: [],
    specifications: [{ label: "Air Output", value: "50 lb/min @ 50 psi" }],
    documents: [],
  },
  {
    id: "eq9",
    assetNo: "BGM-009",
    type: "Cargo Loader",
    manufacturer: "TLD",
    model: "CL-7000",
    bimanSerialNo: "55566",
    TLDSerialNo: "T23918",
    location: "HSIA - Cargo Apron",
    status: "Under Maintenance",
    actualGTDate: "2016-05-14",
    equipmentPhotos: [],
    specifications: [{ label: "Lift Capacity", value: "7,000 kg" }],
    documents: [],
  },
  {
    id: "eq10",
    assetNo: "BGM-010",
    type: "Baggage Tractor",
    manufacturer: "TLD",
    model: "TB-100",
    bimanSerialNo: "66677",
    TLDSerialNo: "CH197",
    location: "HSIA - Apron Bay 4",
    status: "Available",
    actualGTDate: "2021-08-09",
    equipmentPhotos: [],
    specifications: [{ label: "Towing Capacity", value: "10,000 kg" }],
    documents: [],
  },
  {
    id: "eq11",
    assetNo: "BGM-011",
    type: "Baggage Cart",
    manufacturer: "TLD",
    model: "BC-25",
    bimanSerialNo: "77788",
    TLDSerialNo: "310173",
    location: "HSIA - Apron Bay 4",
    status: "Inactive",
    actualGTDate: "2015-04-02",
    equipmentPhotos: [],
    specifications: [{ label: "Capacity", value: "2,500 kg" }],
    documents: [],
  },
  {
    id: "eq12",
    assetNo: "BGM-012",
    type: "Lavatory Service Vehicle",
    manufacturer: "TLD",
    model: "LSV-300",
    bimanSerialNo: "88899",
    TLDSerialNo: "T23724",
    location: "HSIA - Apron Bay 3",
    status: "Available",
    actualGTDate: "2020-10-27",
    equipmentPhotos: [],
    specifications: [{ label: "Tank Capacity", value: "1,200 L" }],
    documents: [],
  },
  {
    id: "eq13",
    assetNo: "BGM-013",
    type: "Potable Water Service Vehicle",
    manufacturer: "TLD",
    model: "PWV-200",
    bimanSerialNo: "99900",
    TLDSerialNo: "T23728",
    location: "HSIA - Apron Bay 3",
    status: "Available",
    actualGTDate: "2020-10-27",
    equipmentPhotos: [],
    specifications: [{ label: "Tank Capacity", value: "900 L" }],
    documents: [],
  },
  {
    id: "eq14",
    assetNo: "BGM-014",
    type: "Ground Power Unit (GPU)",
    manufacturer: "TLD",
    model: "GPU-90",
    bimanSerialNo: "10101",
    TLDSerialNo: "T21516",
    location: "HSIA - Apron Bay 6",
    status: "Available",
    actualGTDate: "2022-06-19",
    equipmentPhotos: [],
    specifications: [{ label: "Output", value: "90 kVA, 115/200V, 400Hz" }],
    documents: [],
  },
];

// ---------------------------------------------------------------------------
// Tickets
// ---------------------------------------------------------------------------

const baseChecklist = (): Ticket["maintenanceRecord"]["inspectionChecklist"] => [
  { id: "c1", label: "Visual inspection for damage/wear", checked: false },
  { id: "c2", label: "Fluid levels checked (oil, hydraulic, coolant)", checked: false },
  { id: "c3", label: "Tyres/wheels condition checked", checked: false },
  { id: "c4", label: "Brakes and steering tested", checked: false },
  { id: "c5", label: "Lights, horn & warning signals functional", checked: false },
];

export const tickets: Ticket[] = [
  {
    id: "t1",
    ticketNo: "PM-2026-001",
    type: "Preventive Maintenance",
    equipmentId: "eq1",
    pmType: "250 Hr Service",
    priority: "Medium",
    status: "Open",
    dueDate: "2026-07-01",
    createdDate: "2026-06-20",
    assignedEngineer: "Engr. Abdul Karim",
    createdBy: "Kamal Hossain",
    requestingParty: "Biman Admin",
    maintenanceRecord: {
      problemDescription: "Scheduled 250 hour preventive service.",
      inspectionChecklist: baseChecklist(),
      rootCause: "",
      repairActivity: "",
      correctiveAction: "",
      partsUsed: "",
      labourHours: 0,
      engineerNotes: "",
      functionalTestPassed: false,
      safetyCheckPassed: false,
      finalApproval: false,
    },
    history: [
      { id: "h1", label: "Ticket created", timestamp: "2026-06-20T09:00:00", actor: "Kamal Hossain" },
    ],
  },
  {
    id: "t2",
    ticketNo: "BM-2026-018",
    type: "Breakdown Maintenance",
    equipmentId: "eq2",
    faultDescription: "Hydraulic leak from main lift cylinder",
    priority: "High",
    status: "In Progress",
    dueDate: "2026-06-26",
    createdDate: "2026-06-25",
    assignedEngineer: "Engr. Rakib Hasan",
    createdBy: "Kamal Hossain",
    requestingParty: "Biman Admin",
    maintenanceRecord: {
      problemDescription: "Operator reported hydraulic fluid pooling under tow bar during towing operations.",
      inspectionChecklist: baseChecklist().map((c) => ({ ...c, checked: true })),
      rootCause: "Worn seal on main lift cylinder.",
      repairActivity: "Cylinder removed for seal replacement.",
      correctiveAction: "Replace cylinder seal kit, refill hydraulic fluid, bleed system.",
      partsUsed: "Seal kit HK-2201",
      labourHours: 4,
      engineerNotes: "Awaiting seal kit delivery to complete repair.",
      functionalTestPassed: false,
      safetyCheckPassed: false,
      finalApproval: false,
    },
    history: [
      { id: "h1", label: "Ticket created", timestamp: "2026-06-25T08:10:00", actor: "Kamal Hossain" },
      { id: "h2", label: "Assigned to Engr. Rakib Hasan", timestamp: "2026-06-25T09:00:00", actor: "Nusrat Jahan" },
      { id: "h3", label: "Work started", timestamp: "2026-06-25T10:30:00", actor: "Engr. Rakib Hasan" },
    ],
  },
  {
    id: "t3",
    ticketNo: "GM-2026-005",
    type: "General Maintenance",
    equipmentId: "eq5",
    faultDescription: "Cabin light not working",
    priority: "Low",
    status: "Open",
    dueDate: "2026-06-30",
    createdDate: "2026-06-24",
    createdBy: "Kamal Hossain",
    requestingParty: "Biman Admin",
    maintenanceRecord: {
      problemDescription: "Cabin interior light not turning on.",
      inspectionChecklist: baseChecklist(),
      rootCause: "",
      repairActivity: "",
      correctiveAction: "",
      partsUsed: "",
      labourHours: 0,
      engineerNotes: "",
      functionalTestPassed: false,
      safetyCheckPassed: false,
      finalApproval: false,
    },
    history: [
      { id: "h1", label: "Ticket created", timestamp: "2026-06-24T13:00:00", actor: "Kamal Hossain" },
    ],
  },
  {
    id: "t4",
    ticketNo: "PM-2026-021",
    type: "Preventive Maintenance",
    equipmentId: "eq4",
    pmType: "250 Hr Service",
    priority: "Medium",
    status: "Awaiting Verification",
    dueDate: "2026-06-28",
    createdDate: "2026-06-15",
    assignedEngineer: "Engr. Abdul Karim",
    createdBy: "Farhan Ahmed",
    requestingParty: "NGGL Super Admin (on behalf of Biman)",
    maintenanceRecord: {
      problemDescription: "Scheduled 250 hour preventive service.",
      inspectionChecklist: baseChecklist().map((c) => ({ ...c, checked: true })),
      rootCause: "N/A",
      repairActivity: "Lubrication, filter replacement, torque check on step assembly.",
      correctiveAction: "N/A - preventive only.",
      partsUsed: "Oil filter OF-110, Grease 2x",
      labourHours: 3,
      engineerNotes: "All checks passed, ready for verification.",
      functionalTestPassed: true,
      safetyCheckPassed: true,
      finalApproval: false,
    },
    history: [
      { id: "h1", label: "Ticket created", timestamp: "2026-06-15T09:00:00", actor: "Farhan Ahmed" },
      { id: "h2", label: "Assigned to Engr. Abdul Karim", timestamp: "2026-06-15T09:30:00", actor: "Nusrat Jahan" },
      { id: "h3", label: "Work completed", timestamp: "2026-06-21T15:00:00", actor: "Engr. Abdul Karim" },
      { id: "h4", label: "Submitted for verification", timestamp: "2026-06-21T15:05:00", actor: "Engr. Abdul Karim" },
    ],
  },
  {
    id: "t5",
    ticketNo: "BM-2026-019",
    type: "Breakdown Maintenance",
    equipmentId: "eq9",
    faultDescription: "Main lift motor overheating",
    priority: "High",
    status: "Awaiting Parts",
    dueDate: "2026-06-27",
    createdDate: "2026-06-22",
    assignedEngineer: "Engr. Rakib Hasan",
    createdBy: "Kamal Hossain",
    requestingParty: "Biman Admin",
    maintenanceRecord: {
      problemDescription: "Lift motor cuts out and overheats under load.",
      inspectionChecklist: baseChecklist().map((c) => ({ ...c, checked: true })),
      rootCause: "Motor bearing failure.",
      repairActivity: "Motor removed for bearing replacement.",
      correctiveAction: "Replace motor bearing set, test under load.",
      partsUsed: "Bearing set BR-440",
      labourHours: 6,
      engineerNotes: "Requested replacement bearing set - awaiting approval from Biman Admin.",
      functionalTestPassed: false,
      safetyCheckPassed: false,
      finalApproval: false,
    },
    history: [
      { id: "h1", label: "Ticket created", timestamp: "2026-06-22T08:00:00", actor: "Kamal Hossain" },
      { id: "h2", label: "Assigned to Engr. Rakib Hasan", timestamp: "2026-06-22T08:40:00", actor: "Nusrat Jahan" },
      { id: "h3", label: "Equipment/parts requested", timestamp: "2026-06-22T14:00:00", actor: "Engr. Rakib Hasan" },
    ],
  },
  {
    id: "t6",
    ticketNo: "WS-2026-011",
    type: "Washing Schedule",
    equipmentId: "eq1",
    pmType: "Weekly Wash",
    priority: "Low",
    status: "Completed",
    dueDate: "2026-06-20",
    createdDate: "2026-06-19",
    assignedEngineer: "Engr. Shirin Sultana",
    createdBy: "Kamal Hossain",
    requestingParty: "Biman Admin",
    closedDate: "2026-06-20",
    downtimeHours: 1,
    maintenanceRecord: {
      problemDescription: "Routine weekly wash.",
      inspectionChecklist: baseChecklist().map((c) => ({ ...c, checked: true })),
      rootCause: "N/A",
      repairActivity: "Full exterior wash, degrease undercarriage.",
      correctiveAction: "N/A",
      partsUsed: "N/A",
      labourHours: 1,
      engineerNotes: "Completed without issue.",
      functionalTestPassed: true,
      safetyCheckPassed: true,
      finalApproval: true,
    },
    history: [
      { id: "h1", label: "Ticket created", timestamp: "2026-06-19T08:00:00", actor: "Kamal Hossain" },
      { id: "h2", label: "Work completed", timestamp: "2026-06-20T09:00:00", actor: "Engr. Shirin Sultana" },
      { id: "h3", label: "Verified & closed", timestamp: "2026-06-20T09:30:00", actor: "Engr. Shirin Sultana" },
    ],
  },
  {
    id: "t7",
    ticketNo: "PM-2026-014",
    type: "Preventive Maintenance",
    equipmentId: "eq3",
    pmType: "Monthly Service",
    priority: "Medium",
    status: "Closed",
    dueDate: "2026-06-02",
    createdDate: "2026-05-28",
    assignedEngineer: "Engr. Abdul Karim",
    createdBy: "Farhan Ahmed",
    requestingParty: "NGGL Super Admin (on behalf of Biman)",
    closedDate: "2026-06-02",
    downtimeHours: 2,
    maintenanceRecord: {
      problemDescription: "Scheduled monthly service.",
      inspectionChecklist: baseChecklist().map((c) => ({ ...c, checked: true })),
      rootCause: "N/A",
      repairActivity: "Filter change, battery water top-up, output test.",
      correctiveAction: "N/A",
      partsUsed: "Air filter AF-90",
      labourHours: 2,
      engineerNotes: "All parameters within spec.",
      functionalTestPassed: true,
      safetyCheckPassed: true,
      finalApproval: true,
    },
    history: [
      { id: "h1", label: "Ticket created", timestamp: "2026-05-28T09:00:00", actor: "Farhan Ahmed" },
      { id: "h2", label: "Work completed", timestamp: "2026-06-02T11:00:00", actor: "Engr. Abdul Karim" },
      { id: "h3", label: "Verified & closed", timestamp: "2026-06-02T11:30:00", actor: "Engr. Abdul Karim" },
    ],
  },
  {
    id: "t8",
    ticketNo: "BM-2026-020",
    type: "Breakdown Maintenance",
    equipmentId: "eq5",
    faultDescription: "Compressor not engaging",
    priority: "High",
    status: "Closed",
    dueDate: "2026-06-10",
    createdDate: "2026-06-05",
    assignedEngineer: "Engr. Rakib Hasan",
    createdBy: "Kamal Hossain",
    requestingParty: "Biman Admin",
    closedDate: "2026-06-11",
    downtimeHours: 30,
    maintenanceRecord: {
      problemDescription: "AC output cold air stopped, compressor clutch not engaging.",
      inspectionChecklist: baseChecklist().map((c) => ({ ...c, checked: true })),
      rootCause: "Faulty compressor clutch relay.",
      repairActivity: "Replaced relay and tested compressor cycle.",
      correctiveAction: "Relay replaced, system recharged.",
      partsUsed: "Relay RLY-12, Refrigerant 2kg",
      labourHours: 5,
      engineerNotes: "Unit still flagged out of service pending final electrical audit.",
      functionalTestPassed: true,
      safetyCheckPassed: true,
      finalApproval: true,
    },
    history: [
      { id: "h1", label: "Ticket created", timestamp: "2026-06-05T08:00:00", actor: "Kamal Hossain" },
      { id: "h2", label: "Work completed", timestamp: "2026-06-10T16:00:00", actor: "Engr. Rakib Hasan" },
      { id: "h3", label: "Verified & closed", timestamp: "2026-06-11T09:00:00", actor: "Engr. Rakib Hasan" },
    ],
  },
  {
    id: "t9",
    ticketNo: "WS-2026-012",
    type: "Washing Schedule",
    equipmentId: "eq7",
    pmType: "Weekly Wash",
    priority: "Low",
    status: "Open",
    dueDate: "2026-06-29",
    createdDate: "2026-06-24",
    createdBy: "Kamal Hossain",
    requestingParty: "Biman Admin",
    maintenanceRecord: {
      problemDescription: "Routine weekly wash.",
      inspectionChecklist: baseChecklist(),
      rootCause: "",
      repairActivity: "",
      correctiveAction: "",
      partsUsed: "",
      labourHours: 0,
      engineerNotes: "",
      functionalTestPassed: false,
      safetyCheckPassed: false,
      finalApproval: false,
    },
    history: [
      { id: "h1", label: "Ticket created", timestamp: "2026-06-24T08:00:00", actor: "Kamal Hossain" },
    ],
  },
  {
    id: "t10",
    ticketNo: "PM-2026-022",
    type: "Preventive Maintenance",
    equipmentId: "eq6",
    pmType: "500 Hr Service",
    priority: "Medium",
    status: "Assigned",
    dueDate: "2026-07-04",
    createdDate: "2026-06-23",
    assignedEngineer: "Engr. Abdul Karim",
    createdBy: "Kamal Hossain",
    requestingParty: "Biman Admin",
    maintenanceRecord: {
      problemDescription: "Scheduled 500 hour preventive service.",
      inspectionChecklist: baseChecklist(),
      rootCause: "",
      repairActivity: "",
      correctiveAction: "",
      partsUsed: "",
      labourHours: 0,
      engineerNotes: "",
      functionalTestPassed: false,
      safetyCheckPassed: false,
      finalApproval: false,
    },
    history: [
      { id: "h1", label: "Ticket created", timestamp: "2026-06-23T09:00:00", actor: "Kamal Hossain" },
      { id: "h2", label: "Assigned to Engr. Abdul Karim", timestamp: "2026-06-23T09:30:00", actor: "Nusrat Jahan" },
    ],
  },
  {
    id: "t11",
    ticketNo: "GM-2026-006",
    type: "General Maintenance",
    equipmentId: "eq8",
    faultDescription: "Loose panel cover",
    priority: "Low",
    status: "In Progress",
    dueDate: "2026-06-28",
    createdDate: "2026-06-25",
    assignedEngineer: "Engr. Rakib Hasan",
    createdBy: "Kamal Hossain",
    requestingParty: "Biman Admin",
    maintenanceRecord: {
      problemDescription: "Side access panel cover is loose and rattling.",
      inspectionChecklist: baseChecklist().map((c) => ({ ...c, checked: true })),
      rootCause: "Missing fasteners.",
      repairActivity: "Replacing fasteners and re-securing panel.",
      correctiveAction: "Install M6 fasteners.",
      partsUsed: "Fasteners M6 x4",
      labourHours: 1,
      engineerNotes: "In progress, near completion.",
      functionalTestPassed: false,
      safetyCheckPassed: false,
      finalApproval: false,
    },
    history: [
      { id: "h1", label: "Ticket created", timestamp: "2026-06-25T10:00:00", actor: "Kamal Hossain" },
      { id: "h2", label: "Assigned to Engr. Rakib Hasan", timestamp: "2026-06-25T10:30:00", actor: "Nusrat Jahan" },
      { id: "h3", label: "Work started", timestamp: "2026-06-25T11:00:00", actor: "Engr. Rakib Hasan" },
    ],
  },
  {
    id: "t12",
    ticketNo: "PM-2026-023",
    type: "Preventive Maintenance",
    equipmentId: "eq10",
    pmType: "250 Hr Service",
    priority: "Medium",
    status: "Open",
    dueDate: "2026-06-25",
    createdDate: "2026-06-10",
    createdBy: "Kamal Hossain",
    requestingParty: "Biman Admin",
    maintenanceRecord: {
      problemDescription: "Scheduled 250 hour preventive service - overdue.",
      inspectionChecklist: baseChecklist(),
      rootCause: "",
      repairActivity: "",
      correctiveAction: "",
      partsUsed: "",
      labourHours: 0,
      engineerNotes: "",
      functionalTestPassed: false,
      safetyCheckPassed: false,
      finalApproval: false,
    },
    history: [
      { id: "h1", label: "Ticket created", timestamp: "2026-06-10T09:00:00", actor: "Kamal Hossain" },
    ],
  },
  {
    id: "t13",
    ticketNo: "WS-2026-013",
    type: "Washing Schedule",
    equipmentId: "eq9",
    pmType: "Weekly Wash",
    priority: "Low",
    status: "Open",
    dueDate: "2026-06-22",
    createdDate: "2026-06-15",
    createdBy: "Kamal Hossain",
    requestingParty: "Biman Admin",
    maintenanceRecord: {
      problemDescription: "Routine weekly wash - overdue.",
      inspectionChecklist: baseChecklist(),
      rootCause: "",
      repairActivity: "",
      correctiveAction: "",
      partsUsed: "",
      labourHours: 0,
      engineerNotes: "",
      functionalTestPassed: false,
      safetyCheckPassed: false,
      finalApproval: false,
    },
    history: [
      { id: "h1", label: "Ticket created", timestamp: "2026-06-15T08:00:00", actor: "Kamal Hossain" },
    ],
  },
  {
    id: "t14",
    ticketNo: "BM-2026-021",
    type: "Breakdown Maintenance",
    equipmentId: "eq11",
    faultDescription: "Wheel bearing seized",
    priority: "Medium",
    status: "Closed",
    dueDate: "2026-05-20",
    createdDate: "2026-05-15",
    assignedEngineer: "Engr. Shirin Sultana",
    createdBy: "Kamal Hossain",
    requestingParty: "Biman Admin",
    closedDate: "2026-05-19",
    downtimeHours: 96,
    maintenanceRecord: {
      problemDescription: "Cart will not roll, wheel bearing seized.",
      inspectionChecklist: baseChecklist().map((c) => ({ ...c, checked: true })),
      rootCause: "Bearing corrosion due to water ingress.",
      repairActivity: "Wheel and bearing assembly replaced.",
      correctiveAction: "Sealed bearing housing installed.",
      partsUsed: "Wheel bearing WB-20",
      labourHours: 3,
      engineerNotes: "Cart taken out of active rotation, flagged inactive pending review.",
      functionalTestPassed: true,
      safetyCheckPassed: true,
      finalApproval: true,
    },
    history: [
      { id: "h1", label: "Ticket created", timestamp: "2026-05-15T09:00:00", actor: "Kamal Hossain" },
      { id: "h2", label: "Work completed", timestamp: "2026-05-18T14:00:00", actor: "Engr. Shirin Sultana" },
      { id: "h3", label: "Verified & closed", timestamp: "2026-05-19T09:00:00", actor: "Engr. Shirin Sultana" },
    ],
  },
  {
    id: "t15",
    ticketNo: "PM-2026-024",
    type: "Preventive Maintenance",
    equipmentId: "eq12",
    pmType: "Monthly Service",
    priority: "Medium",
    status: "Closed",
    dueDate: "2026-06-01",
    createdDate: "2026-05-25",
    assignedEngineer: "Engr. Abdul Karim",
    createdBy: "Farhan Ahmed",
    requestingParty: "NGGL Super Admin (on behalf of Biman)",
    closedDate: "2026-05-30",
    downtimeHours: 2,
    maintenanceRecord: {
      problemDescription: "Scheduled monthly service.",
      inspectionChecklist: baseChecklist().map((c) => ({ ...c, checked: true })),
      rootCause: "N/A",
      repairActivity: "Tank flush, valve inspection.",
      correctiveAction: "N/A",
      partsUsed: "Valve seal kit",
      labourHours: 2,
      engineerNotes: "Completed without issue.",
      functionalTestPassed: true,
      safetyCheckPassed: true,
      finalApproval: true,
    },
    history: [
      { id: "h1", label: "Ticket created", timestamp: "2026-05-25T09:00:00", actor: "Farhan Ahmed" },
      { id: "h2", label: "Work completed", timestamp: "2026-05-29T14:00:00", actor: "Engr. Abdul Karim" },
      { id: "h3", label: "Verified & closed", timestamp: "2026-05-30T10:00:00", actor: "Engr. Abdul Karim" },
    ],
  },
  {
    id: "t16",
    ticketNo: "GM-2026-007",
    type: "General Maintenance",
    equipmentId: "eq14",
    faultDescription: "Control panel display flickering",
    priority: "Medium",
    status: "Awaiting Verification",
    dueDate: "2026-06-27",
    createdDate: "2026-06-20",
    assignedEngineer: "Engr. Rakib Hasan",
    createdBy: "Kamal Hossain",
    requestingParty: "Biman Admin",
    maintenanceRecord: {
      problemDescription: "Digital control panel display flickers intermittently.",
      inspectionChecklist: baseChecklist().map((c) => ({ ...c, checked: true })),
      rootCause: "Loose display ribbon connector.",
      repairActivity: "Reseated ribbon connector, cleaned contacts.",
      correctiveAction: "Connector reseated and secured.",
      partsUsed: "N/A",
      labourHours: 1.5,
      engineerNotes: "Ready for verification.",
      functionalTestPassed: true,
      safetyCheckPassed: true,
      finalApproval: false,
    },
    history: [
      { id: "h1", label: "Ticket created", timestamp: "2026-06-20T09:00:00", actor: "Kamal Hossain" },
      { id: "h2", label: "Work completed", timestamp: "2026-06-24T15:00:00", actor: "Engr. Rakib Hasan" },
      { id: "h3", label: "Submitted for verification", timestamp: "2026-06-24T15:05:00", actor: "Engr. Rakib Hasan" },
    ],
  },
  {
    id: "t17",
    ticketNo: "WS-2026-014",
    type: "Washing Schedule",
    equipmentId: "eq13",
    pmType: "Weekly Wash",
    priority: "Low",
    status: "Assigned",
    dueDate: "2026-06-23",
    createdDate: "2026-06-21",
    assignedEngineer: "Engr. Shirin Sultana",
    createdBy: "Kamal Hossain",
    requestingParty: "Biman Admin",
    maintenanceRecord: {
      problemDescription: "Routine weekly wash.",
      inspectionChecklist: baseChecklist(),
      rootCause: "",
      repairActivity: "",
      correctiveAction: "",
      partsUsed: "",
      labourHours: 0,
      engineerNotes: "",
      functionalTestPassed: false,
      safetyCheckPassed: false,
      finalApproval: false,
    },
    history: [
      { id: "h1", label: "Ticket created", timestamp: "2026-06-21T08:00:00", actor: "Kamal Hossain" },
      { id: "h2", label: "Assigned to Engr. Shirin Sultana", timestamp: "2026-06-21T08:30:00", actor: "Nusrat Jahan" },
    ],
  },
];

// ---------------------------------------------------------------------------
// Equipment / Parts Requests
// ---------------------------------------------------------------------------

export const equipmentRequests: EquipmentRequest[] = [
  {
    id: "r1",
    requestNo: "REQ-2026-001",
    item: "Hydraulic seal kit HK-2201",
    quantity: 1,
    reason: "Main lift cylinder seal replacement",
    ticketId: "t2",
    equipmentId: "eq2",
    requestedBy: "Engr. Rakib Hasan",
    requestedDate: "2026-06-25",
    status: "Pending",
  },
  {
    id: "r2",
    requestNo: "REQ-2026-002",
    item: "Motor bearing set BR-440",
    quantity: 2,
    reason: "Lift motor bearing failure",
    ticketId: "t5",
    equipmentId: "eq9",
    requestedBy: "Engr. Rakib Hasan",
    requestedDate: "2026-06-22",
    status: "Pending",
  },
  {
    id: "r3",
    requestNo: "REQ-2026-003",
    item: "Compressor relay RLY-12",
    quantity: 1,
    reason: "AC compressor clutch not engaging",
    ticketId: "t8",
    equipmentId: "eq5",
    requestedBy: "Engr. Rakib Hasan",
    requestedDate: "2026-06-06",
    status: "Approved",
    approvedBy: "Kamal Hossain",
    approvedDate: "2026-06-07",
  },
  {
    id: "r4",
    requestNo: "REQ-2026-004",
    item: "Air filter AF-90",
    quantity: 1,
    reason: "Scheduled monthly service replacement part",
    ticketId: "t7",
    equipmentId: "eq3",
    requestedBy: "Engr. Abdul Karim",
    requestedDate: "2026-05-29",
    status: "Received",
    approvedBy: "Kamal Hossain",
    approvedDate: "2026-05-29",
  },
  {
    id: "r5",
    requestNo: "REQ-2026-005",
    item: "Wheel bearing WB-20",
    quantity: 1,
    reason: "Seized wheel bearing replacement",
    ticketId: "t14",
    equipmentId: "eq11",
    requestedBy: "Engr. Shirin Sultana",
    requestedDate: "2026-05-16",
    status: "Received",
    approvedBy: "Kamal Hossain",
    approvedDate: "2026-05-16",
  },
  {
    id: "r6",
    requestNo: "REQ-2026-006",
    item: "M6 fasteners (pack of 10)",
    quantity: 1,
    reason: "Loose access panel cover",
    ticketId: "t11",
    equipmentId: "eq8",
    requestedBy: "Engr. Rakib Hasan",
    requestedDate: "2026-06-25",
    status: "Rejected",
    approvedBy: "Kamal Hossain",
    approvedDate: "2026-06-25",
  },
  {
    id: "r7",
    requestNo: "REQ-2026-007",
    item: "Valve seal kit",
    quantity: 1,
    reason: "Monthly tank valve inspection",
    ticketId: "t15",
    equipmentId: "eq12",
    requestedBy: "Engr. Abdul Karim",
    requestedDate: "2026-05-26",
    status: "Received",
    approvedBy: "Kamal Hossain",
    approvedDate: "2026-05-26",
  },
];

// ---------------------------------------------------------------------------
// Maintenance schedules
// ---------------------------------------------------------------------------

export const maintenanceSchedules: MaintenanceSchedule[] = [
  {
    id: "sch1",
    scheduleNo: "SCH-2026-001",
    type: "Preventive Maintenance",
    equipmentId: "eq1",
    activity: "250 Hr Service",
    frequency: "Every 250 hours",
    lastDate: "2026-04-01",
    dueDate: "2026-07-05",
    scheduleDuration: "4 days",
    status: "Overdue",
    ticketId: "t1",
    assignedEngineer: "Engr. Abdul Karim",
  },
  {
    id: "sch2",
    scheduleNo: "SCH-2026-002",
    type: "Washing",
    equipmentId: "eq2",
    activity: "Weekly exterior wash",
    frequency: "Every 7 days",
    lastDate: "2026-06-18",
    dueDate: "2026-06-26",
    scheduleDuration: "1 day",
    status: "Overdue",
    assignedEngineer: "Engr. Shirin Sultana",
  },
  {
    id: "sch3",
    scheduleNo: "SCH-2026-003",
    type: "Preventive Maintenance",
    equipmentId: "eq3",
    activity: "Monthly service",
    frequency: "Every 1 month",
    lastDate: "2026-05-02",
    dueDate: "2026-06-30",
    scheduleDuration: "28 days",
    status: "In progress",
    assignedEngineer: "Engr. Abdul Karim",
  },
  {
    id: "sch4",
    scheduleNo: "SCH-2026-004",
    type: "Washing",
    equipmentId: "eq4",
    activity: "Weekly exterior wash",
    frequency: "Every 7 days",
    lastDate: "2026-06-19",
    dueDate: "2026-06-27",
    scheduleDuration: "1 day",
    status: "Due soon",
  },
  {
    id: "sch5",
    scheduleNo: "SCH-2026-005",
    type: "Preventive Maintenance",
    equipmentId: "eq6",
    activity: "Monthly service",
    frequency: "Every 1 month",
    lastDate: "2026-06-01",
    dueDate: "2026-07-03",
    scheduleDuration: "2 days",
    status: "Scheduled",
  },
  {
    id: "sch6",
    scheduleNo: "SCH-2026-006",
    type: "Washing",
    equipmentId: "eq7",
    activity: "Weekly exterior wash",
    frequency: "Every 7 days",
    lastDate: "2026-06-22",
    dueDate: "2026-06-30",
    scheduleDuration: "1 day",
    status: "Scheduled",
  },
  {
    id: "sch7",
    scheduleNo: "SCH-2026-007",
    type: "Preventive Maintenance",
    equipmentId: "eq8",
    activity: "250 Hr Service",
    frequency: "Every 250 hours",
    lastDate: "2026-04-18",
    dueDate: "2026-07-20",
    scheduleDuration: "2 days",
    status: "Scheduled",
  },
  {
    id: "sch8",
    scheduleNo: "SCH-2026-008",
    type: "Washing",
    equipmentId: "eq9",
    activity: "Weekly exterior wash",
    frequency: "Every 7 days",
    lastDate: "2026-06-08",
    dueDate: "2026-06-23",
    scheduleDuration: "1 day",
    status: "Completed",
    ticketId: "t6",
  },
];

// ---------------------------------------------------------------------------
// Notifications
// ---------------------------------------------------------------------------

export const notifications: AppNotification[] = [
  {
    id: "n1",
    type: "Overdue PM",
    message: "PM-2026-023 (Baggage Tractor BGM-010) preventive maintenance is overdue.",
    timestamp: "2026-06-26T07:00:00",
    read: false,
  },
  {
    id: "n2",
    type: "Washing Due",
    message: "WS-2026-013 (Cargo Loader BGM-009) washing schedule is overdue.",
    timestamp: "2026-06-26T07:00:00",
    read: false,
  },
  {
    id: "n3",
    type: "Battery Water Top-up",
    message: "GPU 90 KVA (BGM-003) battery water top-up is due.",
    timestamp: "2026-06-25T16:00:00",
    read: false,
  },
  {
    id: "n4",
    type: "Insurance Expiry",
    message: "GPU 90 KVA (BGM-003) insurance expires on 10-Jul-26.",
    timestamp: "2026-06-25T09:00:00",
    read: false,
  },
  {
    id: "n5",
    type: "New Request",
    message: "Engr. Rakib Hasan requested Hydraulic seal kit HK-2201 for BM-2026-018.",
    timestamp: "2026-06-25T10:05:00",
    read: false,
  },
  {
    id: "n6",
    type: "Request Approved",
    message: "Compressor relay RLY-12 request for BM-2026-020 was approved by Kamal Hossain.",
    timestamp: "2026-06-07T09:00:00",
    read: true,
  },
  {
    id: "n7",
    type: "Request Rejected",
    message: "M6 fasteners request for GM-2026-006 was rejected by Kamal Hossain.",
    timestamp: "2026-06-25T11:00:00",
    read: false,
  },
  {
    id: "n8",
    type: "Overdue PM",
    message: "PM-2026-001 (Belt Loader BGM-001) 250 hour service is due 01-Jul-26.",
    timestamp: "2026-06-24T07:00:00",
    read: true,
  },
];

// Derived views kept for screens that need flattened relationships.
export const requests = equipmentRequests;
export const documents = equipment.flatMap((item) =>
  item.documents.map((document) => ({
    id: document.id,
    name: document.name,
    assetNo: item.assetNo,
    expiry: document.expiryDate,
    type: document.type,
  })),
);

export const getEquipment = (id: string) => equipment.find((item) => item.id === id);
export const getTicket = (id: string) => tickets.find((ticket) => ticket.id === id);
